### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by Tiantian089** [qiuhuaqi/cardiac-motion#11]
Hi, I've run through this code. But I have some confusion about the results which contain the warped_label_ES,  sa_dvf , etc.  
1) Does 'warped_label_ES' mean the result of warping the segmentation of ES frame to ED frame?
2) I thought the output would contain segmentation result, but I didn't found it.  Which folder would contain the segmentation result? 
Thank you for your patient reading, and look forward to your reply.

**Comment by qiuhuaqi** [comment]
Hi again,

I assume your questions about the output of `inference.py`:
1. Yes.
2. This framework only does image registration (motion estimation) but not segmentation. Segmentation is only used here to evaluate the quality of the registration. So you would have to supply the ED and ES frame segmentation volumes to the evaluation dataset/dataloader yourself. 


This research code was developed quite a while earlier. So some of its design choices are not so good and can be quite confusing at times. Sorry about that. We do have plans for an overhaul in the future.

**Comment by Tiantian089** [comment]
Hi again,
I have got what you mean due to your patient explanation. Thank you a lot!

You motioned that the **cardiac** ED and ES frame segmentation volumes are provided for evaluation the quality of **cardiac** motion estimation.
That inspired me to supply  the **myocardiac** ED and ES frame segmentation volumes to the evaluation dataset for the **myocardiac** motion estimation, but the result is confusing
         1. The value of  myo metrics(dice_myo_std, dice_myo_mean, mcd_myo_mean, etc) are NaN, but LV metrics have numbers.
         2. And the dvf is not confined to the myocardium.

Do that means I could not estimate myocardium motion by this project?

Thank you for your patient reading, and look forward to your reply.

**Comment by qiuhuaqi** [comment]
1. I suspect that's from the label's numerical value. If you are only supplying segmentation of myocardium it's likely to be labelled as **1**. That would be recognised as LV by the code. You can see the label values for the structures in these lines: 
https://github.com/qiuhuaqi/cardiac-motion/blob/e23aa094b3e352a3a1026d31333c3caf016df09a/cardiac_motion/eval.py#L101
You can change the `label_class` value to match the structure. 

2. The estimated DVF shouldn't be limited to the myocardium by design. This framework estimates cardiac motion via _unsupervised_ image registration, on the entire image space. What people usually do is mask out the estimated motion with myocardium segmentation before further analysis.

**Comment by Tiantian089** [comment]
Hey again,
 I've totally run through this code, thank you very much for your kind help!!
 But I'm still feel confused about the outputs which I don't know how to use them. Does 'sa_dvf' , for example, represent the  result of motion estimation?
 And I'm still wondering whether this project can realize the fecture tracking of myocardium and calculate the corresponding circumentrial and radial strain of myocardium.

Thanks!!!

**Comment by qiuhuaqi** [comment]
Hi. Glad to hear that.
The `sa_dvf` should be the short axis dense displacement vector field. It tells you, at each point, how the pixel/tissue is estimated to move from the ES frame to the ED frame (or the other way around, depends on which order you put in your data, DVF is always estimated from `target` to `source` in this framework). 

I don't have the code to compute myocardium strains here. But if you want to compute strains, the idea is you use this estimated DVF to transform a myocardium shape model of some sort (typically derived from the myocardium segmentation), and calculate the circumferential or radial change of the lengths of segments on the shape model.
